sudo: required
services:
    - docker

before_install:
    - docker build -t sifer357/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sifer357/docker-react npm run test -- --coverage