sudo: required
services:
    - docker

before_install:
    - docker build -t sifer357/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sifer357/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "docker-react-app"
    env: "DockerReactApp-env"
    bucket_name: "elasticbeanstalk-us-east-2-138086560928"
    bucket_path: "docker-react-app"
#    on: 
#        branch: master
